# Makefile for Examples 
# TODO: add executables for rest of example files

all: BasicStats_example

VPATH = ../SourceCode/BasicStats

BasicStats_example: BasicStats.o BasicStats_example.cpp
	g++ -o BasicStats_example BasicStats_example.cpp