# Makefile for Examples 
# TODO: add executables for rest of example files

all: BasicStats_example

CC = g++
FLAGS = -std=c++11
VPATH = ../SourceCode/BasicStats

BasicStats_example: BasicStats_example.cpp BasicStats.o
	$(CC) -o $@ $<