// Gnuplots data generated by VarySize, VaryMemory, or VaryBins

#include <iostream>
#include <stdio.h>
#include <stdlib.h>
using namespace std;

int main(int argc, char* argv[])
{
  if (argc < 4)
  {
    cout << "usage: MakePlot [S|M|B] input-file output-file [0|1]\n";
    return 0;
  }
  FILE* file;
  char command[256];

  file = fopen("plot.p", "w");

  fprintf(file, "set term postscript eps color\n");
  fprintf(file, "set output \"%s.eps\"\n", argv[3]);

  fprintf(file, "set xlabel '%s'\n", argv[1]);
  fprintf(file, "set ylabel 'Relative Error'\n");

  fprintf(file, "set key box\n");
  fprintf(file, "set size 1,1\n");
 
  if (argv[1][0] == 'S')
    fprintf(file, "set logscale x\n");
  //fprintf(file, "set yrange [0:*]\n");
  fprintf(file, "set logscale y\n");

  if (argc < 4)
    fprintf(file, "plot \"%s\" u 1:2 t 'GK' w lines\n", argv[2]);
  else
    fprintf(file, "plot \"%s\" u 1:2 t 'GK' w lines, \"%s\" u 1:2 t 'Q-Digest' w lines, \"%s\" u 1:2 t 'Reservoir-Sampling' w lines\n", argv[2], argv[2], argv[2]);

  fclose(file);
  
  system("gnuplot plot.p");
  sprintf(command, "convert %s.eps %s.jpg", argv[3], argv[3]);
  system(command);

  //system("rm plot.p");
  return 0;
}
